services:
  app:
    build: .
    container_name: inventaris-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/inventaris
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:               # expose ke host
      - "8080:8080"      # host:container
    networks:
      - inventaris-net

  db:
    image: mysql:8.0
    container_name: inventaris-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: inventaris
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inventaris-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: inventaris-phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"
    networks:
      - inventaris-net

  nginx:
    image: nginx:alpine
    container_name: inventaris-nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - inventaris-net

networks:
  inventaris-net:
    driver: bridge

volumes:
  db_data:
